/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficas;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class FrmGraficas extends javax.swing.JFrame {

    boolean inicioTrazo;
    int x1, y1;

    Dibujo d;

    boolean seleccionando;

    public FrmGraficas() {
        initComponents();
        inicioTrazo = false;
        d = new Dibujo();
        seleccionando = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGraficas = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnAbrir = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JToggleButton();
        txtResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlGraficas.setBackground(new java.awt.Color(255, 204, 204));
        pnlGraficas.setForeground(new java.awt.Color(255, 204, 255));
        pnlGraficas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGraficasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlGraficasLayout = new javax.swing.GroupLayout(pnlGraficas);
        pnlGraficas.setLayout(pnlGraficasLayout);
        pnlGraficasLayout.setHorizontalGroup(
            pnlGraficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlGraficasLayout.setVerticalGroup(
            pnlGraficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Abrir.png"))); // NOI18N
        btnAbrir.setFocusable(false);
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAbrir);

        btnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Seleccionar.png"))); // NOI18N
        btnSeleccionar.setFocusable(false);
        btnSeleccionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSeleccionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSeleccionar);

        txtResultado.setEditable(false);
        jToolBar1.add(txtResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
            .addComponent(pnlGraficas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGraficas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlGraficasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGraficasMouseClicked
        int x = evt.getX();
        int y = evt.getY();
        Graphics g = pnlGraficas.getGraphics();

        if (!btnSeleccionar.isSelected()) {

            txtResultado.setText("x=" + String.valueOf(x) + ", y=" + String.valueOf(y));

            if (!inicioTrazo) {
                inicioTrazo = true;
                x1 = x;
                y1 = y;
            } else {
                inicioTrazo = false;

                g.setColor(Color.red);

                g.drawLine(x1, y1, x, y);
                int ancho = x - x1 + 1;
                if (x < x1) {
                    ancho = -ancho;
                    x1 = x;
                }
                int alto = y - y1;
                if (y < y1) {
                    alto = -alto;
                    y1 = y;
                }
                g.setColor(Color.blue);
                g.drawRect(x1, y1, ancho, alto);

                g.setColor(Color.GREEN);
                g.drawOval(x1, y1, ancho, alto);

            }
        } else {
            Primitiva p = d.buscar(x, y);
            if (p != null) {
                d.dibujar(pnlGraficas);
                int x1 = p.getX1() > p.getX2() ? p.getX2() : p.getX1();
                int y1 = p.getY1() > p.getY2() ? p.getY2() : p.getY1();
                g.setColor(Color.red);
                g.fillRect(x1, y1, p.getAncho(), p.getAlto());
            }

        }

    }//GEN-LAST:event_pnlGraficasMouseClicked

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        String nombreArchivo = Archivo.elegirArchivo("Seleccionar archivo", "Abrir", "*.*", "Todos los archivos");
        txtResultado.setText(nombreArchivo);
        if (nombreArchivo.length() > 0) {
            d.desdeArchivo(nombreArchivo);
            d.dibujar(pnlGraficas);
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGraficas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGraficas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGraficas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGraficas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGraficas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JToggleButton btnSeleccionar;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnlGraficas;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
